SELECT ADHERENTS.NOADHERENT, ADHERENTS.NOM, ADHERENTS.PRENOM, COUNT(EMPRUNTS.NOLIVRE) AS TOTAL_LIVRES_EMPRUNTES
                FROM biblio.adherents
                         JOIN biblio.emprunts ON ADHERENTS.NOADHERENT = EMPRUNTS.NOADHERENT
                GROUP BY ADHERENTS.NOADHERENT
                HAVING COUNT(EMPRUNTS.NOLIVRE) > 0;